// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: images.sql

package db

import (
	"context"
)

const createImage = `-- name: CreateImage :one
INSERT INTO images (
  photo
) VALUES (
  $1
)
RETURNING id, photo
`

func (q *Queries) CreateImage(ctx context.Context, photo []byte) (Images, error) {
	row := q.db.QueryRowContext(ctx, createImage, photo)
	var i Images
	err := row.Scan(&i.ID, &i.Photo)
	return i, err
}

const getRanDomImage = `-- name: GetRanDomImage :one
SELECT id, photo
FROM images
ORDER BY random()
LIMIT 1
`

func (q *Queries) GetRanDomImage(ctx context.Context) (Images, error) {
	row := q.db.QueryRowContext(ctx, getRanDomImage)
	var i Images
	err := row.Scan(&i.ID, &i.Photo)
	return i, err
}
