// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	CreateImage(ctx context.Context, photo []byte) (Images, error)
	GetRanDomImage(ctx context.Context) (Images, error)
}

var _ Querier = (*Queries)(nil)
